// Simula el uso de las pantallas en un navegador simulado (jsdom) y verifica que no haya errores.
const { JSDOM } = require('jsdom'), assert = require('assert'), path = require('path'), XLSX = require('xlsx');
(async () => {
  const errores = [], alerts = [];
  const dom = await JSDOM.fromFile(path.join(__dirname, '../index.html'), { runScripts: 'dangerously', resources: 'usable', pretendToBeVisual: true,
    beforeParse(w) { w.XLSX = XLSX; w.TextEncoder = TextEncoder; Object.defineProperty(w, 'crypto', { value: require('crypto').webcrypto }); w.scrollTo = () => {}; w.alert = m => alerts.push(m); w.confirm = () => true; w.URL.createObjectURL = () => 'blob:x'; w.URL.revokeObjectURL = () => {}; w.HTMLAnchorElement.prototype.click = function () {};
      w.open = () => ({ document: { write() {}, close() {} }, focus() {}, print() {} });
      w.HTMLDialogElement.prototype.showModal = function () { this.returnValue = 'ok'; if (w.__fill) { const f = w.__fill; w.__fill = null; f(this); } setTimeout(() => this.onclose && this.onclose(), 0); };
      w.addEventListener('error', e => errores.push(e.message)); w.addEventListener('unhandledrejection', e => errores.push(String(e.reason))); } });
  const w = dom.window, d = w.document, sleep = ms => new Promise(r => setTimeout(r, ms)), $ = s => d.querySelector(s), fill = (dlg, o) => Object.entries(o).forEach(([k, v]) => { dlg.querySelector('#f' + k).value = v; });
  const nav = async t => { if (t === 'ventas') w.go('ventas'); else (t === 'cfg' ? $('#bneg') : $(`[data-t=${t}]`)).click(); await sleep(150); };
  await sleep(800);
  // ---- ingreso: arranca en oscuro y se elige el usuario (sin textos de "con/sin contraseña")
  assert($('#login').classList.contains('on') && d.documentElement.dataset.theme === 'dark', 'arranca en la pantalla de ingreso y en modo oscuro'); assert(!/(con|sin) contrase/i.test($('#login').textContent), 'no dice con/sin contraseña');
  assert.strictEqual(w.getComputedStyle($('header')).display, 'none', 'sin encabezado en el ingreso');
  // ---- empleado: apertura de caja y salón
  w.__fill = x => fill(x, { 0: 20000 }); $('#u-emp').click(); await sleep(500);
  assert.strictEqual((await w.pilo.cajaHoy()).apertura, 20000, 'apertura de caja del empleado'); assert((await w.pilo.cajaHoy()).abierta);
  assert($('#salon').classList.contains('on') && d.querySelectorAll('#plano .tbl').length === 11, 'salón con las 11 mesas'); assert($('#salon .side [data-t=viandas]') && $('#salon .side [data-t=clientes]') && $('#salon .side [data-t=caja]'), 'botones Viandas, Clientes y Caja y gastos'); assert.strictEqual($('#salon [data-t=clientes] .i svg').dataset.n, 'persona', 'ícono de persona en Clientes');
  { const hd = $('header'), bg = w.getComputedStyle(hd).backgroundColor, jc = w.getComputedStyle(hd).justifyContent; assert(['', 'transparent', 'rgba(0, 0, 0, 0)'].includes(bg) && jc !== 'center', 'el encabezado no hereda los estilos de las barras del gráfico (' + bg + '/' + jc + ')'); assert.strictEqual(w.getComputedStyle($('#bneg')).display, 'none', 'Mi Negocio oculto para el empleado'); assert.strictEqual($('#ses').textContent, 'Empleado'); }
  // edición de mesas (posición y tamaño): se activa y muestra las manijas
  $('#bplano').click(); await sleep(150); assert(d.querySelectorAll('#plano .tbl.mv').length === 11 && d.querySelectorAll('#plano .rz').length === 11, 'modo edición con manijas de tamaño'); $('#plano .tbl[data-m="Mesa 3"]').click(); await sleep(100); assert($('#salon').classList.contains('on'), 'en edición no se abre la mesa'); $('#bplano').click(); await sleep(150); assert.strictEqual(d.querySelectorAll('#plano .rz').length, 0);
  // modo oscuro / claro
  const t0 = d.documentElement.dataset.theme; $('#tema').click(); assert.notStrictEqual(d.documentElement.dataset.theme, t0, 'cambia el tema'); $('#tema').click(); assert.strictEqual(d.documentElement.dataset.theme, t0);
  // mesa: productos con íconos, orden propio y cobro
  $('#plano .tbl[data-m="Mesa 2"]').click(); await sleep(300); assert($('#ventas').classList.contains('on') && /Mesa 2/.test($('#tt').textContent) && $('#ventas').classList.contains('emp') && $('#back').textContent.includes('Salón'), 'tocar la mesa abre sus productos');
  assert.strictEqual(w.getComputedStyle($('#mesas')).display, 'none', 'el empleado no ve la fila de mesas en la cuenta');
  { const icos = {}; for (const c of [...d.querySelectorAll('#cats .chip')]) { if (c.textContent === 'Viandas') continue; c.click(); await sleep(150); d.querySelectorAll('#prods .prod').forEach(b => { icos[[...b.childNodes].find(n => n.nodeType === 3).textContent.trim()] = b.querySelector('.pi svg').dataset.n; }); }
    assert.strictEqual(icos['Cortado'], 'cafe', 'cafetería: café'); assert.strictEqual(icos['Milanesa al plato'], 'plato', 'al plato: plato'); assert(['Hamburguesa', 'Lomo completo', 'Sándwich de milanesa simple', 'Tostado'].every(n => icos[n] === 'hamb'), 'sándwiches: hamburguesa'); assert.strictEqual(icos['Carne'], 'empanada', 'empanadas'); assert.strictEqual(icos['Medialuna'], 'medialuna', 'panadería: medialuna'); assert(!Object.values(icos).includes('cubiertos'), 'ningún producto queda con el ícono genérico'); }
  $('#cats .chip').click(); await sleep(150); { const nombres = () => [...d.querySelectorAll('#prods .prod')].map(b => b.dataset.i); const antes = nombres(); assert(antes.length > 2);
    $('#bord').click(); await sleep(250); assert(d.querySelectorAll('#prods .prod.mv').length === antes.length && $('#hord').classList.contains('on'), 'modo ordenar botones');
    await w.reordenar(+antes[0], +antes[2]); await sleep(300);
    const dsp = nombres(); assert.deepStrictEqual(dsp.slice(0, 3), [antes[1], antes[2], antes[0]], 'el botón toma el lugar del botón de destino'); assert.deepStrictEqual(JSON.parse((await w.pilo.config())['pref:emp:orden']).slice(0, 2).length, 2, 'orden guardado para el empleado');
    $('#bord').click(); await sleep(250); $(`#prods .prod[data-i="${dsp[0]}"]`).click(); await sleep(100); assert.strictEqual(d.querySelectorAll('#items .it').length, 1, 'fuera del modo ordenar el botón agrega productos'); }
  $('#prods .prod').click(); await sleep(100); assert.match($('#tot').textContent, /\d/, 'cuenta con total'); const tot0 = (await w.pilo.stats()).hoy;
  $('[data-m].btn[data-m="Efectivo"]').click(); await sleep(300); assert($('#salon').classList.contains('on'), 'al cobrar vuelve al salón'); assert((await w.pilo.stats()).hoy > tot0, 'venta cobrada'); assert.strictEqual($('#plano .tbl[data-m="Mesa 2"]').classList.contains('libre'), true, 'la mesa queda libre');
  // gastos: la caja muestra solo los de hoy
  { const f = new Date(); f.setDate(f.getDate() - 1); const ayer = f.getFullYear() + '-' + String(f.getMonth() + 1).padStart(2, '0') + '-' + String(f.getDate()).padStart(2, '0'); await w.pilo.gasto({ categoria: 'Insumos', proveedor: 'Prov', monto: 1500, medio: 'Efectivo' }); await w.pilo.gasto({ categoria: 'Alquiler', monto: 900, fecha: ayer, medio: 'Transferencia' });
    await nav('caja'); assert($('#gl').textContent.includes('Insumos') && $('#gl').textContent.includes('Total de hoy') && !$('#gl').textContent.includes('Alquiler'), 'Caja y gastos: solo gastos de hoy'); }
  // la venta de la mesa para los siguientes pasos
  assert.strictEqual((await w.pilo.stats()).hoy > 0, true);

  // clientes
  await nav('clientes'); w.__fill = x => fill(x, { 0: 'Laura', 1: '3412223333', 2: 'Calle Falsa 123', 3: 'sin cebolla' }); $('#bncl').click(); await sleep(250);
  const laura = (await w.pilo.clientes()).find(c => c.nombre === 'Laura'); assert(laura && laura.direccion === 'Calle Falsa 123' && laura.observaciones === 'sin cebolla', 'cliente guardado');
  assert($('#cll').textContent.includes('Calle Falsa 123'), 'cliente en la lista'); $('#qcl').value = 'zzz'; $('#qcl').oninput(); await sleep(150); assert($('#cll').textContent.includes('No hay clientes')); $('#qcl').value = ''; $('#qcl').oninput();
  // viandas desde Ventas: cliente de la lista + cliente nuevo
  await nav('ventas'); const chip = () => [...d.querySelectorAll('#cats .chip')].find(c => c.textContent === 'Viandas');
  let nota = ''; w.__fill = x => { fill(x, { 0: laura.id, 4: '12:30', 5: 2, 6: '1', 7: 'Transferencia', 8: 'sin sal' }); x.querySelector('#f5').dispatchEvent(new w.Event('input', { bubbles: true })); nota = x.querySelector('#dnote').textContent; }; chip().click(); await sleep(300);
  assert($('#viandas').classList.contains('on'), 'abre la pestaña Viandas'); assert(nota.includes('17.800') && nota.includes('envío'), 'el cuadro muestra el total que cambia con cantidad, modalidad y pago: ' + nota);
  assert.strictEqual(d.querySelector('#dlg select option[value="0"]') && 0, 0); 
  await nav('ventas'); w.__fill = x => fill(x, { 0: '', 1: 'Pedro', 3: 'Mitre 55', 4: '11:15', 6: '0', 7: 'Transferencia' }); chip().click(); await sleep(300);
  const tv = $('#vh').textContent; assert(tv.includes('Laura') && tv.includes('Calle Falsa 123') && tv.includes('Con envío') && tv.includes('Pedro') && tv.includes('A retirar') && tv.includes('Retira en el local'), 'viandas con cliente, dirección y modalidad');
  assert(tv.indexOf('Pedro') < tv.indexOf('Laura'), 'ordenadas por horario'); assert(tv.includes('sin sal'), 'observaciones de la vianda en la lista'); assert($('#vres').textContent.includes('transferencia'));
  { const h0 = (await w.pilo.stats()).hoy; $('#vh [data-e]').click(); await sleep(250); assert.strictEqual((await w.pilo.stats()).hoy, h0 + 7900, 'vianda entregada y cobrada (Pedro: retira, transferencia = 7900)'); }
  w.__fill = x => fill(x, { 1: '0', 4: 'Efectivo', 3: 1 }); $('#vh [data-ed]').click(); await sleep(250); assert.match($('#vh').textContent, /A retirar/); assert.match($('#vh').textContent, /7\.500/, 'Laura pasa a retirar y pagar en efectivo = 7500'); assert($('#ve').textContent.includes('Pedro'));
  // admin: todas las pestañas y detalle del día
  $('#lgn').click(); await sleep(200); assert($('#login').classList.contains('on') && !d.body.classList.contains('adm'), 'cambiar usuario vuelve al ingreso'); $('#u-adm').click(); assert($('#pw').classList.contains('on')); $('#pwi').value = 'mal'; $('#pwok').click(); await sleep(400); assert($('#pwe').textContent.includes('incorrecta'), 'contraseña incorrecta'); assert(!d.body.classList.contains('adm')); $('#pwi').value = 'admin'; $('#pwok').click(); await sleep(900); assert.strictEqual((await w.pilo.config())['pref:adm:orden'], undefined, 'el administrador tiene su propio orden de botones'); assert(d.body.classList.contains('adm'), 'login de administrador'); assert($('#hk').textContent.includes('Ganancia del mes') && $('#hvend').style.display !== 'none', 'inicio del administrador con ganancias'); assert.notStrictEqual(w.getComputedStyle($('.tile[data-t=stats]')).display, 'none');
  assert($('.sq svg'), 'iconos de color en los títulos');
  $('#home .tile.big').click(); await sleep(300); assert($('#salon').classList.contains('on') && d.querySelectorAll('#plano .tbl').length === 11, 'el administrador también tiene el salón con las mesas'); assert.notStrictEqual(w.getComputedStyle($('#back')).display, 'none', 'el administrador puede volver al inicio desde el salón'); assert($('#back').textContent.includes('Inicio'));
  assert($('#salon .side [data-t=viandas]') && $('#salon .side [data-t=clientes]') && $('#salon .side [data-t=caja]'), 'el administrador ve Viandas, Clientes y Caja y gastos en el salón'); $('#bplano').click(); await sleep(200); assert.strictEqual(d.querySelectorAll('#plano .rz').length, 11, 'el administrador puede editar las mesas'); $('#bplano').click(); await sleep(150);
  $('#plano .tbl[data-m="Mesa 7"]').click(); await sleep(300); assert($('#ventas').classList.contains('on') && /Mesa 7/.test($('#tt').textContent) && $('#back').textContent.includes('Salón'), 'el administrador abre la mesa'); $('#bord').click(); await sleep(200); assert(d.querySelectorAll('#prods .prod.mv').length > 0, 'el administrador puede ordenar los botones'); $('#bord').click(); await sleep(150);
  $('#prods .prod').click(); await sleep(100); $('[data-m].btn[data-m="QR"]').click(); await sleep(300); assert($('#salon').classList.contains('on'), 'el administrador cobra y vuelve al salón'); $('#back').click(); await sleep(250); assert($('#home').classList.contains('on'), 'volver al inicio del administrador'); assert.notStrictEqual(w.getComputedStyle($('#bneg')).display, 'none', 'Mi Negocio visible para el administrador'); assert(!$('#inn'), 'el nombre ya no está duplicado en Configuración');
  await w.pilo.setConfig('logo', 'data:image/png;base64,iVBORw0KGgo='); await nav('cfg'); assert($('#cfg').classList.contains('on'), 'Mi Negocio abre la pantalla de configuración'); assert(/Mi Negocio/.test($('#cfg h1').textContent), 'título Mi Negocio'); assert(!$('.tile[data-t=cfg]') && !d.querySelector('#dneg'), 'ya no hay mosaico Productos y ajustes ni cuadro aparte');
  for (const [id, v] of [['#inm', 'Café Uri'], ['#idir', 'San Martín 123'], ['#itel', '3462 555555']]) { $(id).value = v; $(id).onchange({ target: $(id) }); await sleep(120); }
  assert.strictEqual($('#nm').textContent, 'Café Uri', 'nombre del negocio'); assert($('#nsub').textContent.includes('San Martín 123') && $('#nsub').textContent.includes('3462 555555'), 'dirección y teléfono'); assert($('#lg img'), 'logo en el encabezado'); assert.strictEqual((await w.pilo.config()).direccion, 'San Martín 123', 'guardado');
  await nav('cfg'); assert($('#clogo img'), 'logo en Mi Negocio'); assert.strictEqual($('#inm').value, 'Café Uri'); assert($('#pv1') && $('#pl .pl') && $('#bpw') && $('#bdl') && $('input[type=color]') && $('#bpc'), 'todo lo de Configuración está dentro de Mi Negocio');
  $('#inm').value = ''; $('#inm').onchange({ target: $('#inm') }); await sleep(250); assert.strictEqual($('#nm').textContent, 'Café Uri', 'el nombre no puede quedar vacío'); assert.strictEqual($('#inm').value, 'Café Uri'); $('#cquit').click(); await sleep(150); assert(!$('#lg img'), 'quitar logo');
  // quitar una vianda de la lista desde la pantalla (con el cuadro propio de confirmación)
  await w.pilo.agregarVianda({ cliente_id: laura.id, horario: '15:00', cantidad: 1, envio: false, medio: 'Efectivo' }); await nav('viandas'); { const q0 = d.querySelectorAll('#vh [data-q]').length; assert(q0 > 0); [...d.querySelectorAll('#vh [data-q]')].pop().click(); await sleep(300); assert.strictEqual(d.querySelectorAll('#vh [data-q]').length, q0 - 1, 'vianda quitada'); }
  // precios de viandas en Configuración
  await nav('cfg'); $('#pv1').value = '8000'; $('#pv1').onchange({ target: $('#pv1') }); await sleep(200); assert.strictEqual((await w.pilo.preciosViandas()).efectivo, 8000); assert($('#pvx').textContent.includes('8.000') && $('#pvx').textContent.includes('9.000'), 'ejemplos de precios'); $('#pv1').value = '7500'; $('#pv1').onchange({ target: $('#pv1') }); await sleep(150);
  assert(!d.querySelector('#aviso-version'), 'sin aviso de archivos desactualizados');
  // productos: eliminar y aumentar precios
  await nav('cfg'); const n0 = (await w.pilo.productos()).length, med0 = (await w.pilo.productos()).find(x => x.nombre === 'Medialuna').precio, fact0 = (await w.pilo.productos()).find(x => x.nombre === 'Factura').precio;
  w.__fill = x => { x.querySelector('#pp').value = '10'; [...x.querySelectorAll('.pk')].filter(c => c.parentElement.textContent.includes('Medialuna')).forEach(c => { c.checked = true; }); }; $('#bpc').click(); await sleep(300);
  assert.strictEqual((await w.pilo.productos()).find(x => x.nombre === 'Medialuna').precio, Math.round(med0 * 1.1 / 10) * 10, 'aumento % aplicado al producto elegido'); assert.strictEqual((await w.pilo.productos()).find(x => x.nombre === 'Factura').precio, fact0, 'los no elegidos no cambian');
  $('#pl [data-x]').click(); await sleep(250); assert.strictEqual((await w.pilo.productos()).length, n0 - 1, 'producto eliminado desde la pantalla'); for (const t of ['inicio', 'caja', 'stock', 'stats', 'cfg', 'viandas', 'ventas']) await nav(t);
  await nav('inicio'); const hoy = w.pilo && (await w.pilo.dia(new Date().toISOString().slice(0, 10))); const cel = $('.day.hoy'); assert(cel, 'día de hoy marcado'); cel.click(); await sleep(250);
  assert($('#dia').classList.contains('on'), 'el calendario lleva al día'); assert($('#dv').textContent.includes('Mesa 2') && $('#dv').textContent.includes('Vianda'), 'ventas del día'); assert($('#ds').textContent.includes('Más vendidos') && $('#dk').textContent.includes('Cobrado'), 'estadísticas del día');
  $('#dprev').click(); await sleep(150); assert($('#dv').textContent.includes('No hubo ventas'), 'día anterior sin ventas'); $('#dback').click(); await sleep(150); assert($('#inicio').classList.contains('on')); for (let k = 0; k < 15 && !$('#home').classList.contains('on'); k++) { $('#back').click(); await sleep(120); } assert($('#home').classList.contains('on') && $('#back').style.display === 'none', 'volviendo hacia atrás se llega al inicio'); assert($('#htop').textContent.includes('Cortado') || $('#htop').textContent.includes('Café'), 'más vendidos en el inicio');
  $('#bneg').click(); await sleep(150); w.__fill = null; const pre = $('#inu'); pre.value = 'Uri'; pre.onchange({ target: pre }); await sleep(150); assert.strictEqual($('#av').textContent, 'U'); $('[data-t=inicio]').click(); await sleep(150);
  await nav('stats'); assert(/\$/.test($('#s1').textContent) && /venta/.test($('#s1n').textContent), 'ventas de hoy'); assert.strictEqual(d.querySelectorAll('#stats .kbtn').length, 3, 'tres botones de ganancia');
  { const n = () => d.querySelectorAll('#sgraf rect').length, b = p => $(`#stats .kbtn[data-p=${p}]`);
    assert.strictEqual(n(), new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).getDate(), 'mensual: una barra por día'); assert(b('mes').classList.contains('on'));
    b('anio').click(); await sleep(250); assert.strictEqual(n(), 12, 'anual: una barra por mes'); assert(b('anio').classList.contains('on') && /Año/.test($('#sptit').textContent));
    b('sem').click(); await sleep(250); assert.strictEqual(n(), 7, 'semanal: una barra por día'); assert(/Semana/.test($('#sptit').textContent));
    assert($('#stab').textContent.includes('Efectivo') && $('#stab').textContent.includes('Transferencia') && $('#stab').textContent.includes('Total'), 'tabla por forma de pago');
    const t0 = $('#sptit').textContent; assert($('#spn').disabled, 'no se puede avanzar al futuro'); $('#spv').click(); await sleep(250); assert.notStrictEqual($('#sptit').textContent, t0, 'semana anterior'); assert.strictEqual($('#spn').disabled, false); $('#spn').click(); await sleep(250); assert.strictEqual($('#sptit').textContent, t0); }
  await nav('stats'); { const g = p => $(`#stats [data-g=${p}]`); assert(g('mes').classList.contains('on'), 'gastos: mensual por defecto'); g('dia').click(); await sleep(250); assert($('#gres').textContent.includes('Insumos') && !$('#gres').textContent.includes('Alquiler'), 'gastos del día'); $('#gpv').click(); await sleep(250); assert($('#gres').textContent.includes('Alquiler') && $('#gres').textContent.includes('900'), 'gastos del día anterior'); $('#gpn').click(); await sleep(250); g('anio').click(); await sleep(250); assert($('#gres').textContent.includes('Insumos'), 'gastos del año'); g('sem').click(); await sleep(250); assert($('#gtit').textContent.includes('Semana') && $('#gres').textContent.includes('Categoría') && $('#gres').textContent.includes('Detalle'), 'gastos de la semana con resumen por categoría y detalle'); }
  $('#bxl').click(); $('#bpd').click(); await nav('cfg'); $('#bdl').click(); await sleep(150);
  assert.deepStrictEqual(errores, [], 'sin errores en pantalla'); console.log('OK: pantallas sin errores', alerts.length ? '(avisos: ' + alerts.join(' | ').replace(/\n/g, ' ') + ')' : '');
  process.exit(0);
})().catch(e => { console.error('SMOKE FALLÓ:', e.message); process.exit(1); });
