const assert = require('assert'), PiloStore = require('../src/store'), { excel, html } = require('../src/export'), XLSX = require('xlsx');
const memoria = () => { let v = null; return { load: async () => v, save: async s => { v = s; } }; };
(async () => {
  const st = memoria(), db = await PiloStore.crear(st), hoy = PiloStore.hoy;
  assert(await db.login('admin') && !(await db.login('x')), 'login');
  const p = db.guardarProducto({ categoria: 'Cafetería', nombre: 'Cortado', precio: 3000 }), c = db.cliente({ nombre: 'Juan' });
  const it = [{ producto_id: p, nombre: 'Cortado', cantidad: 2, precio: 3000 }];
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 4000 }, { medio: 'QR', monto: 2000 }] });
  db.cobrar({ items: it, descuento: 500, cliente_id: c, pagos: [{ medio: 'Fiado', monto: 5500 }] });
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 1 }] }), /no suman/);
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Fiado', monto: 6000 }] }), /cliente/);
  db.gasto({ categoria: 'Insumos', monto: 1500 });
  const d = db.mes(hoy().slice(0, 7))[hoy()];
  assert.deepStrictEqual([d.ingresos, d.egresos, d.medios.QR], [6000, 1500, 2000], 'resumen (el fiado no cuenta como ingreso)');
  assert.strictEqual(db.deudaClientes()[0].deuda, 5500);
  db.cobrarDeuda({ cliente_id: c, medio: 'Efectivo', monto: 1000 }); assert.strictEqual(db.deudaClientes()[0].deuda, 4500);
  assert.strictEqual(db.stats().hoy, 7000); db.abrirCaja(20000); assert.strictEqual(db.cajaHoy().esperado, 23500);
  const i1 = db.guardarInsumo({ nombre: 'Café', unidad: 'kg', stock: 1, costo: 20000 }); db.setReceta(p, [{ insumo_id: i1, cantidad: 0.02 }]);
  assert(Math.abs(db.productos().find(x => x.id === p).costo_receta - 400) < 1e-6);
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 6000 }] }); assert(Math.abs(db.insumos()[0].stock - 0.96) < 1e-9, 'stock');
  db.comprarInsumo({ insumo_id: i1, cantidad: 2, monto: 50000 }); assert(Math.abs(db.insumos()[0].stock - 2.96) < 1e-9 && db.insumos()[0].costo === 25000);
  const cAna = db.cliente({ nombre: 'Ana', telefono: '341', direccion: 'Calle 1', observaciones: 'timbre' }); assert.strictEqual(db.clientes().find(x => x.id === cAna).direccion, 'Calle 1');
  db.guardarCliente({ id: cAna, nombre: 'Ana P', telefono: '341', direccion: 'Calle 2', observaciones: '' }); assert.strictEqual(db.clientes().find(x => x.id === cAna).direccion, 'Calle 2', 'editar cliente');
  const pv = db.guardarProducto({ categoria: 'Viandas', nombre: 'Vianda', precio: 7000, p_retiro_transf: 7500, p_envio_efectivo: 8000, p_envio_transf: 8500 });
  const v2 = db.agregarVianda({ cliente_id: cAna, direccion: 'Calle 2', horario: '13:00', producto_id: pv, cantidad: 1, envio: true, medio: 'Transferencia' }), v1 = db.agregarVianda({ cliente_id: cAna, horario: '12:00', producto_id: pv, cantidad: 2, envio: false, medio: 'Efectivo' });
  const L = () => db.viandasLista().pendientes; assert.deepStrictEqual(L().map(x => x.horario), ['12:00', '13:00'], 'viandas ordenadas por horario'); assert.strictEqual(L()[0].cliente, 'Ana P');
  assert.deepStrictEqual([L()[0].total, L()[1].total], [14000, 8500], 'precios: retiro efectivo x2 y envío transferencia'); assert.strictEqual(L()[1].direccion, 'Calle 2'); assert.strictEqual(L()[0].direccion, '', 'a retirar no lleva dirección');
  db.editarVianda(v2, { horario: '13:30', envio: true, direccion: 'X 1', cantidad: 2, medio: 'Efectivo' }); assert.strictEqual(L()[1].total, 16000, 'modificar a envío efectivo'); db.editarVianda(v2, { envio: false, medio: 'Transferencia', cantidad: 1 }); assert.strictEqual(L()[1].total, 7500, 'modificar a retiro transferencia');
  const antes = db.stats().hoy; db.entregarVianda(v1); assert.strictEqual(db.stats().hoy, antes + 14000, 'vianda cobrada'); assert.strictEqual(db.viandasLista().entregadas.length, 1);
  assert.throws(() => db.entregarVianda(v1), /pendiente/); assert.throws(() => db.editarVianda(v1, {}), /pendiente/); db.quitarVianda(v2); assert.strictEqual(L().length, 0);
  assert.strictEqual(db.ajustarPrecios({ ids: [p, pv], porcentaje: 10, redondeo: 10 }), 2); const P = id => db.productos().find(x => x.id === id);
  assert.deepStrictEqual([P(p).precio, P(pv).precio, P(pv).p_retiro_transf, P(pv).p_envio_efectivo, P(pv).p_envio_transf], [3300, 7700, 8250, 8800, 9350], 'aumento % en los productos elegidos y en los 4 precios de la vianda');
  assert.strictEqual(db.productos().find(x => x.nombre === 'Medialuna').precio, 800, 'los no elegidos no cambian'); assert.throws(() => db.ajustarPrecios({ ids: [p], porcentaje: 0 }), /inválido/);
  db.ajustarPrecios({ ids: [p], porcentaje: -10, redondeo: 10 }); assert.strictEqual(P(p).precio, 2970, 'bajar precios');
  db.eliminarProducto(pv); assert(!P(pv), 'producto eliminado'); assert.strictEqual(db.dia(hoy()).ventas.some(v => v.items.some(i => i.nombre.includes('Vianda'))), true, 'las ventas viejas se conservan');
  const dd = db.dia(hoy()); assert(dd.ventas.length >= 4 && dd.top.length > 0 && dd.ingresos > 0 && dd.ventas[0].items.length, 'detalle del día'); assert.strictEqual(db.dia('2000-01-01').ventas.length, 0);
  const rep = db.reporte(hoy().slice(0, 7)); assert.strictEqual(XLSX.read(excel(rep)).SheetNames.length, 4); assert(html(rep).includes('Informe'));
  assert(await db.login('admin')); await db.cambiarClave('nueva'); assert(await db.login('nueva') && !(await db.login('admin')), 'cambio de clave');
  assert(!db.backupVencido(), 'backup al día'); const copia = db.dump();
  await db.flush(); const db2 = await PiloStore.crear(st); assert.strictEqual(db2.productos().length, 25, 'persistencia');
  const db3 = await PiloStore.crear(memoria()); db3.restore(copia); assert.strictEqual(db3.deudaClientes().length, 2, 'restaurar backup'); assert.throws(() => db3.restore('{"x":1}'), /backup/);
  console.log('OK: lógica de datos');
})().catch(e => { console.error('FALLÓ:', e.stack); process.exit(1); });
