const assert = require('assert'), PiloStore = require('../src/store'), { excel, html } = require('../src/export'), XLSX = require('xlsx');
const memoria = () => { let v = null; return { load: async () => v, save: async s => { v = s; } }; };
(async () => {
  const st = memoria(), db = await PiloStore.crear(st), hoy = PiloStore.hoy;
  assert(await db.login('admin') && !(await db.login('x')), 'login');
  const p = db.guardarProducto({ categoria: 'Cafetería', nombre: 'Cortado', precio: 3000 }), c = db.cliente({ nombre: 'Juan' });
  const it = [{ producto_id: p, nombre: 'Cortado', cantidad: 2, precio: 3000 }];
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 4000 }, { medio: 'QR', monto: 2000 }] });
  db.cobrar({ items: it, descuento: 500, cliente_id: c, pagos: [{ medio: 'Fiado', monto: 5500 }] });
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 1 }] }), /no suman/);
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Fiado', monto: 6000 }] }), /cliente/);
  db.gasto({ categoria: 'Insumos', monto: 1500 });
  const d = db.mes(hoy().slice(0, 7))[hoy()];
  assert.deepStrictEqual([d.ingresos, d.egresos, d.medios.QR], [6000, 1500, 2000], 'resumen (el fiado no cuenta como ingreso)');
  assert.strictEqual(db.deudaClientes()[0].deuda, 5500);
  db.cobrarDeuda({ cliente_id: c, medio: 'Efectivo', monto: 1000 }); assert.strictEqual(db.deudaClientes()[0].deuda, 4500);
  assert.strictEqual(db.stats().hoy, 7000); db.abrirCaja(20000); assert.strictEqual(db.cajaHoy().esperado, 23500);
  const i1 = db.guardarInsumo({ nombre: 'Café', unidad: 'kg', stock: 1, costo: 20000 }); db.setReceta(p, [{ insumo_id: i1, cantidad: 0.02 }]);
  assert(Math.abs(db.productos().find(x => x.id === p).costo_receta - 400) < 1e-6);
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 6000 }] }); assert(Math.abs(db.insumos()[0].stock - 0.96) < 1e-9, 'stock');
  db.comprarInsumo({ insumo_id: i1, cantidad: 2, monto: 50000 }); assert(Math.abs(db.insumos()[0].stock - 2.96) < 1e-9 && db.insumos()[0].costo === 25000);
  const cAna = db.cliente({ nombre: 'Ana', telefono: '341', direccion: 'Calle 1', observaciones: 'timbre' }); assert.strictEqual(db.clientes().find(x => x.id === cAna).direccion, 'Calle 1');
  db.guardarCliente({ id: cAna, nombre: 'Ana P', telefono: '341', direccion: 'Calle 2', observaciones: '' }); assert.strictEqual(db.clientes().find(x => x.id === cAna).direccion, 'Calle 2', 'editar cliente');
  assert.deepStrictEqual(db.preciosViandas(), { efectivo: 7500, transferencia: 7900, envio: 1000, envio_max: 2 }, 'precios de viandas por defecto');
  const cv = (e, m, n) => db.calcularVianda(e, m, n).total;
  assert.deepStrictEqual([cv(false, 'Efectivo', 1), cv(false, 'Transferencia', 1), cv(true, 'Efectivo', 1), cv(true, 'Transferencia', 1)], [7500, 7900, 8500, 8900], 'los 4 precios de una vianda');
  assert.deepStrictEqual([cv(true, 'Efectivo', 2), cv(true, 'Efectivo', 3), cv(true, 'Transferencia', 5), cv(false, 'Efectivo', 3)], [17000, 24500, 41500, 22500], 'envío: $1000 por vianda hasta 2 viandas ($2000 máximo)');
  const v2 = db.agregarVianda({ cliente_id: cAna, direccion: 'Calle 2', horario: '13:00', cantidad: 1, envio: true, medio: 'Transferencia', observaciones: ' sin sal ' }), v1 = db.agregarVianda({ cliente_id: cAna, horario: '12:00', cantidad: 2, envio: false, medio: 'Efectivo' });
  const L = () => db.viandasLista().pendientes; assert.deepStrictEqual(L().map(x => x.horario), ['12:00', '13:00'], 'viandas ordenadas por horario'); assert.strictEqual(L()[0].cliente, 'Ana P');
  assert.deepStrictEqual([L()[0].total, L()[1].total], [15000, 8900], 'retira x2 efectivo y envío transferencia'); assert.strictEqual(L()[1].direccion, 'Calle 2'); assert.strictEqual(L()[0].direccion, '', 'a retirar no lleva dirección');
  assert.strictEqual(L()[1].observaciones, 'sin sal', 'observaciones de la vianda'); db.editarVianda(v2, { horario: '13:30', observaciones: 'con sal', envio: true, direccion: 'X 1', cantidad: 2, medio: 'Efectivo' }); assert.strictEqual(L()[1].total, 17000, 'modificar a 2 viandas con envío en efectivo'); assert.strictEqual(L()[1].observaciones, 'con sal', 'modificar observaciones'); db.editarVianda(v2, { envio: true, direccion: 'X 1', medio: 'Efectivo', cantidad: 2 }); assert.strictEqual(L()[1].observaciones, 'con sal', 'si no se toca, las observaciones se conservan'); db.editarVianda(v2, { envio: false, medio: 'Transferencia', cantidad: 1 }); assert.strictEqual(L()[1].total, 7900, 'modificar a retiro con transferencia');
  const antes = db.stats().hoy; db.entregarVianda(v1); assert.strictEqual(db.stats().hoy, antes + 15000, 'vianda cobrada'); assert.strictEqual(db.viandasLista().entregadas.length, 1);
  assert.throws(() => db.entregarVianda(v1), /pendiente/); assert.throws(() => db.editarVianda(v1, {}), /pendiente/); db.quitarVianda(v2); assert.strictEqual(L().length, 0);
  const v3 = db.agregarVianda({ cliente_id: cAna, direccion: 'Z 9', horario: '14:00', cantidad: 3, envio: true, medio: 'Efectivo' }), a2 = db.stats().hoy; db.entregarVianda(v3); assert.strictEqual(db.stats().hoy, a2 + 24500, '3 viandas con envío en efectivo');
  const dv = db.dia(hoy()); assert(dv.ventas.some(v => v.items.some(i => i.nombre === 'Envío' && i.precio === 2000)), 'el envío queda como renglón aparte'); assert(!dv.top.some(x => x[0] === 'Envío') && dv.top.some(x => x[0] === 'Vianda'), 'el envío no cuenta como producto más vendido');
  db.setConfig('vianda_efectivo', '8000'); db.setConfig('vianda_envio', '1500'); assert.deepStrictEqual([cv(true, 'Efectivo', 1), cv(true, 'Efectivo', 3)], [9500, 27000], 'precios de viandas editables');
  db.ajustarPrecios({ ids: [], porcentaje: 10, redondeo: 10, viandas: true }); assert.deepStrictEqual(db.preciosViandas(), { efectivo: 8800, transferencia: 8690, envio: 1650, envio_max: 2 }, 'aumento % también en las viandas');
  assert.throws(() => db.ajustarPrecios({ ids: [], porcentaje: 0, viandas: true }), /inválido/);
  assert.strictEqual(db.ajustarPrecios({ ids: [p], porcentaje: 10, redondeo: 10 }), 1); const P = id => db.productos().find(x => x.id === id);
  assert.strictEqual(P(p).precio, 3300, 'aumento % en el producto elegido'); assert.strictEqual(db.productos().find(x => x.nombre === 'Medialuna').precio, 800, 'los no elegidos no cambian');
  db.ajustarPrecios({ ids: [p], porcentaje: -10, redondeo: 10 }); assert.strictEqual(P(p).precio, 2970, 'bajar precios');
  const tmp = db.guardarProducto({ categoria: 'X', nombre: 'Temporal', precio: 100 }); db.eliminarProducto(tmp); assert(!P(tmp), 'producto eliminado'); assert.strictEqual(dv.ventas.length > 0, true, 'las ventas viejas se conservan');
  const dd = db.dia(hoy()); assert(dd.ventas.length >= 4 && dd.top.length > 0 && dd.ingresos > 0 && dd.ventas[0].items.length, 'detalle del día'); assert.strictEqual(db.dia('2000-01-01').ventas.length, 0);
  { const y = +hoy().slice(0, 4), m = +hoy().slice(5, 7), ym = hoy().slice(0, 7), last = new Date(y, m, 0).getDate(), M = db.mes(ym), sI = Object.values(M).reduce((a, x) => a + x.ingresos, 0), sE = Object.values(M).reduce((a, x) => a + x.egresos, 0);
    const pm = db.periodo({ desde: ym + '-01', hasta: ym + '-' + String(last).padStart(2, '0'), agrupar: 'dia' }); assert.strictEqual(pm.series.length, last, 'una barra por día del mes'); assert.strictEqual(pm.totales.ingresos, sI); assert.strictEqual(pm.totales.egresos, sE); assert.strictEqual(pm.totales.ganancia, sI - sE);
    assert.strictEqual(Object.values(pm.medios).reduce((a, x) => a + x.ingresos, 0), sI, 'la tabla por forma de pago suma el total'); assert(pm.medios.Efectivo.egresos > 0, 'egresos por forma de pago'); assert(!('Fiado' in pm.medios), 'el fiado no es ingreso');
    const pa = db.periodo({ desde: y + '-01-01', hasta: y + '-12-31', agrupar: 'mes' }); assert.strictEqual(pa.series.length, 12, 'una barra por mes'); assert.strictEqual(pa.totales.ingresos, sI, 'anual = mensual si solo hay datos de este mes'); assert.strictEqual(pa.series[m - 1].clave, ym);
    const pw = db.periodo({ desde: hoy(), hasta: hoy(), agrupar: 'dia' }); assert.strictEqual(pw.series.length, 1); assert.strictEqual(pw.totales.ingresos, db.stats().hoy); }
  { const gd = db.dia(hoy()).gastos, gp = db.gastosPeriodo({ desde: hoy(), hasta: hoy() }); assert.strictEqual(gp.total, gd.reduce((a, g) => a + g.monto, 0), 'gastos del día'); assert.strictEqual(gp.lista.length, gd.length); assert(gp.porCategoria.Insumos.n >= 1 && gp.porCategoria.Insumos.total > 0, 'resumen por categoría');
    db.gasto({ categoria: 'Alquiler', monto: 900, fecha: '2000-01-15' }); assert.strictEqual(db.gastosPeriodo({ desde: '2000-01-01', hasta: '2000-12-31' }).total, 900, 'gastos de un año'); assert.strictEqual(db.gastosPeriodo({ desde: '2000-02-01', hasta: '2000-02-28' }).lista.length, 0); assert.strictEqual(db.gastosPeriodo({ desde: hoy(), hasta: hoy() }).total, gp.total, 'los gastos de otros días no entran en el día'); }
  const rep = db.reporte(hoy().slice(0, 7)); assert.strictEqual(XLSX.read(excel(rep)).SheetNames.length, 4); assert(html(rep).includes('Informe'));
  db.setConfig('direccion', 'San Martín 123'); db.setConfig('telefono', '3462 555555'); db.setConfig('logo', 'data:image/png;base64,AAAA'); const r2 = db.reporte(hoy().slice(0, 7)); assert(html(r2).includes('San Martín 123') && html(r2).includes('3462 555555') && html(r2).includes('data:image/png'), 'PDF con datos del negocio');
  assert(await db.login('admin')); await db.cambiarClave('nueva'); assert(await db.login('nueva') && !(await db.login('admin')), 'cambio de clave');
  assert(!db.backupVencido(), 'backup al día'); const copia = db.dump();
  await db.flush(); const db2 = await PiloStore.crear(st); assert.strictEqual(db2.productos().length, 25, 'persistencia');
  const db3 = await PiloStore.crear(memoria()); await db3.restore(copia); assert.strictEqual(db3.deudaClientes().length, 2, 'restaurar backup'); assert.throws(() => db3.restore('{"x":1}'), /backup/);
  console.log('OK: lógica de datos');
})().catch(e => { console.error('FALLÓ:', e.stack); process.exit(1); });
