const assert = require('assert'), PiloStore = require('../src/store'), { excel, html } = require('../src/export'), XLSX = require('xlsx');
const memoria = () => { let v = null; return { load: async () => v, save: async s => { v = s; } }; };
(async () => {
  const st = memoria(), db = await PiloStore.crear(st), hoy = PiloStore.hoy;
  assert(await db.login('admin') && !(await db.login('x')), 'login');
  const p = db.guardarProducto({ categoria: 'Cafetería', nombre: 'Cortado', precio: 3000 }), c = db.cliente({ nombre: 'Juan' });
  const it = [{ producto_id: p, nombre: 'Cortado', cantidad: 2, precio: 3000 }];
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 4000 }, { medio: 'QR', monto: 2000 }] });
  db.cobrar({ items: it, descuento: 500, cliente_id: c, pagos: [{ medio: 'Fiado', monto: 5500 }] });
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 1 }] }), /no suman/);
  assert.throws(() => db.cobrar({ items: it, pagos: [{ medio: 'Fiado', monto: 6000 }] }), /cliente/);
  db.gasto({ categoria: 'Insumos', monto: 1500 });
  const d = db.mes(hoy().slice(0, 7))[hoy()];
  assert.deepStrictEqual([d.ingresos, d.egresos, d.medios.QR], [6000, 1500, 2000], 'resumen (el fiado no cuenta como ingreso)');
  assert.strictEqual(db.deudaClientes()[0].deuda, 5500);
  db.cobrarDeuda({ cliente_id: c, medio: 'Efectivo', monto: 1000 }); assert.strictEqual(db.deudaClientes()[0].deuda, 4500);
  assert.strictEqual(db.stats().hoy, 7000); db.abrirCaja(20000); assert.strictEqual(db.cajaHoy().esperado, 23500);
  const i1 = db.guardarInsumo({ nombre: 'Café', unidad: 'kg', stock: 1, costo: 20000 }); db.setReceta(p, [{ insumo_id: i1, cantidad: 0.02 }]);
  assert(Math.abs(db.productos().find(x => x.id === p).costo_receta - 400) < 1e-6);
  db.cobrar({ items: it, pagos: [{ medio: 'Efectivo', monto: 6000 }] }); assert(Math.abs(db.insumos()[0].stock - 0.96) < 1e-9, 'stock');
  db.comprarInsumo({ insumo_id: i1, cantidad: 2, monto: 50000 }); assert(Math.abs(db.insumos()[0].stock - 2.96) < 1e-9 && db.insumos()[0].costo === 25000);
  const v = db.guardarVianda({ cliente: 'Ana', precio: 7000, dias: 'dom,lun,mar,mie,jue,vie,sab' }); assert.strictEqual(db.viandasHoy().length, 1);
  db.entregarVianda(v, 'Fiado'); assert.strictEqual(db.viandasHoy().length, 0); assert.strictEqual(db.deudaClientes().find(x => x.nombre === 'Ana').deuda, 7000);
  const rep = db.reporte(hoy().slice(0, 7)); assert.strictEqual(XLSX.read(excel(rep)).SheetNames.length, 4); assert(html(rep).includes('Informe'));
  assert(await db.login('admin')); await db.cambiarClave('nueva'); assert(await db.login('nueva') && !(await db.login('admin')), 'cambio de clave');
  assert(!db.backupVencido(), 'backup al día'); const copia = db.dump();
  await db.flush(); const db2 = await PiloStore.crear(st); assert.strictEqual(db2.productos().length, 25, 'persistencia');
  const db3 = await PiloStore.crear(memoria()); db3.restore(copia); assert.strictEqual(db3.deudaClientes().length, 2, 'restaurar backup'); assert.throws(() => db3.restore('{"x":1}'), /backup/);
  console.log('OK: lógica de datos');
})().catch(e => { console.error('FALLÓ:', e.stack); process.exit(1); });
